id = "glaude"
name = "Le Glaude"
description = "Silicon Valley gave us Claude. France strikes back with Le Glaude."
version = "1.3.5"
schema_version = 1
authors = ["Romain Hardouin"]
repository = "https://github.com/rhardouin/Le-Glaude"

[agent_servers.glaude]
name = "Le Glaude"
icon = "./icons/glaude.svg"

[agent_servers.glaude.targets.darwin-aarch64]
archive = "https://github.com/rhardouin/Le-Glaude/releases/download/v1.3.5/glaude-acp-darwin-aarch64-1.3.5.zip"
cmd = "./glaude-acp"

[agent_servers.glaude.targets.darwin-x86_64]
archive = "https://github.com/rhardouin/Le-Glaude/releases/download/v1.3.5/glaude-acp-darwin-x86_64-1.3.5.zip"
cmd = "./glaude-acp"

[agent_servers.glaude.targets.linux-aarch64]
archive = "https://github.com/rhardouin/Le-Glaude/releases/download/v1.3.5/glaude-acp-linux-aarch64-1.3.5.zip"
cmd = "./glaude-acp"

[agent_servers.glaude.targets.linux-x86_64]
archive = "https://github.com/rhardouin/Le-Glaude/releases/download/v1.3.5/glaude-acp-linux-x86_64-1.3.5.zip"
cmd = "./glaude-acp"

[agent_servers.glaude.targets.windows-aarch64]
archive = "https://github.com/rhardouin/Le-Glaude/releases/download/v1.3.5/glaude-acp-windows-aarch64-1.3.5.zip"
cmd = "./glaude-acp.exe"

[agent_servers.glaude.targets.windows-x86_64]
archive = "https://github.com/rhardouin/Le-Glaude/releases/download/v1.3.5/glaude-acp-windows-x86_64-1.3.5.zip"
cmd = "./glaude-acp.exe"
